export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESSFUL  = 'FETCH_WEATHER_SUCCESSFUL';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const CHANGE_CITY = 'CHANGE_CITY';
export const CHANGE_CITY_SUCCESSFUL = 'CHANGE_CITY_SUCCESSFUL';
export const CHANGE_CITY_FAILURE = 'CHANGE_CITY_FAILURE';

